In [1]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.3'

## create a numpay array

In [2]:

my_np_array =  np.array(
    [1,2,3]
)
print(my_np_array)

[1 2 3]


# Numpy properties: dtype, shape, ndim

In [3]:
print(my_np_array)
print(type(my_np_array))   
print(my_np_array.dtype)      # print data type 
print(my_np_array.shape)      # print shape the array
print(my_np_array.ndim)       # print number of dimention of the array 


[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


# create an array with all zeros

In [4]:
zeros_np_array = np.zeros(
    shape = (5,)
)
print(zeros_np_array)

[0. 0. 0. 0. 0.]


# Create an array with all ones

In [5]:
ones_np_array = np.ones(
    shape = (10,2),
    dtype = 'int'
)
print(ones_np_array)
print(ones_np_array.dtype)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
int64


# Create an array with a specific value

In [6]:
assigned_with_specific_np_array = np.full(
    shape = (10, ),
    fill_value = 15
)
assigned_with_specific_np_array

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

# Create an identity matrix 
'''[1 0 0]
   [0 1 0]
   [0 0 1] 
'''
This is I3 matrix



In [7]:
id_matrix = np.eye(4)
print(id_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Create an empty matrix

In [8]:
my_empty_np_array = np.empty(
    shape = (5,)
)
my_empty_np_array

array([0., 0., 0., 0., 0.])

# Type cast Conversion to dtype 

In [9]:
print(my_empty_np_array.dtype)
my_empty_np_array_int = my_empty_np_array.astype('int')
print(my_empty_np_array_int)
print(my_empty_np_array_int.dtype)

float64
[0 0 0 0 0]
int64


# Create a sequential array

In [10]:
my_array = np.arange(1,10,1)
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# use linspace :  start, A, B, C, stop

In [11]:
my_np_array = np.linspace(
    start = 0,
    stop = 10,
    num = 5
)
my_np_array

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Numpy array dimensions Mathematical objects 

- scalar -> 0D
- vector -> 1D
- matrix -> 2D
- tensor ->xD where x>2
Tensor is a unit data type of pyTorch and Tensorflow

In [12]:
my_0d_array = np.array(45)
print('0-dimensional array:', my_0d_array, ' Number of dimension:',my_0d_array.ndim)

my_1d_array = np.array(
    [1,2,3,4,5]
)
print('1 Dimensional array:', my_1d_array,'Number of dimensional:',my_1d_array.ndim)

my_2d_array = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [7,1,2,7]
    ]
)
print('2-dimensional array: ')
print(my_2d_array)
print("number of dimentional: ",my_2d_array.ndim)

0-dimensional array: 45  Number of dimension: 0
1 Dimensional array: [1 2 3 4 5] Number of dimensional: 1
2-dimensional array: 
[[1 2 3 4]
 [5 6 7 8]
 [7 1 2 7]]
number of dimentional:  2


In [13]:
zeros_np_array = np.zeros(
    shape=(5,3,7)
)

print(zeros_np_array.shape)

(5, 3, 7)


In [14]:
""" Numpy indexing
1. Non-negative indexing (0, 1, 2, ...)
2. Negative indexing (-1, -2, ...)
"""

my_np_array = np.array(
    [1, 2, 3, 4, 5]
)

print(my_np_array[2])
print(my_np_array[-3])

3
3


In [15]:
my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 5],
     [7, 1, 2, 7]]
) 

print(my_2d_array[1,1])
print(my_2d_array[1,-3])

8
8


"""numpy slicing
    - array_name[start:end] => open interval [start, end)
    - array_name[start:end:step]
    - end index is excluded
    - default values: start=0, end=n, step=1
"""* 

In [16]:
my_1d_array = np.array(
    [1, 2, 3, 4, 5]
)

print(my_1d_array[::])
print(my_1d_array[2:5])
print(my_1d_array[1:5:2])

[1 2 3 4 5]
[3 4 5]
[2 4]


In [17]:
my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 5],
     [7, 1, 2, 7]]
) 

print(my_2d_array[0:2,1:3])

print(my_2d_array[1:3,])

[[2 3]
 [8 9]]
[[5 8 9 5]
 [7 1 2 7]]
